GET http://localhost:3000/
Content-Type: application/json

###

GET http://localhost:3000/employee
Content-Type: application/json

###

POST http://localhost:3000/employee
Content-Type: application/json

{
  "first_name": "x",
  "last_name": "xx",
  "position": "backend"
}