### Route Documentation

GET http://localhost:3000/
Content-Type: application/json

### Get Employee

GET http://localhost:3000/employee
Content-Type: application/json

### Add Employee

POST http://localhost:3000/employee
Content-Type: application/json

{
  "first_name": "febri",
  "last_name": "adji",
  "position": "backend"
}

### Get Employee By NIK

GET http://localhost:3000/employee/1000000001
Content-Type: application/json

### Update Employee

PUT http://localhost:3000/employee/1000000001
Content-Type: application/json

{
  "first_name": "febri",
  "last_name": "adji",
  "position": "backend",
  "date_of_birth": "2002/02/26",
  "gender": "male",
  "residence": "jakarta, indonesia",
  "salary": 18000000
}

###

PATCH http://localhost:3000/employee/1000000001
Content-Type: application/json

{
  "position": "backend",
  "residence": "jakarta, indonesia",
  "salary": 18000000
}

### Delete Employee

DELETE http://localhost:3000/employee/1000000015
Content-Type: application/json

### Get Employee By Job Position

GET http://localhost:3000/employee/position/backend
Content-Type: application/json